version: '3.8'

services:
  backend_gateway:
    build: ./backend
    container_name: backpack_gateway
    ports:
      - "8080:8080"
    environment:
      - TARGET_BACKEND_URL=http://dummy_backend:3001
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    restart: always
    networks:
      - backpack_network
    depends_on:
      - dummy_backend

  dummy_backend:
    build: ./backend
    container_name: backpack_dummy
    ports:
      - "3001:3001"
    command: uvicorn dummy_backend:app --host 0.0.0.0 --port 3001
    restart: always
    networks:
      - backpack_network

  frontend_dashboard:
    build: ./frontend
    container_name: backpack_dashboard
    ports:
      - "3000:3000"
    restart: always
    networks:
      - backpack_network
    depends_on:
      - backend_gateway

networks:
  backpack_network:
    driver: bridge
